FROM ubuntu:bionic
LABEL maintainer="devops@nhsx.uk"
LABEL php="7.3"
ENV DEBIAN_FRONTEND noninteractive

RUN \
  apt-get update && \
  apt-get install \
    curl \
    gpg-agent \
    software-properties-common \
    supervisor \
    --no-install-recommends -y && \
    add-apt-repository -y ppa:ondrej/nginx-mainline && \
    add-apt-repository -y ppa:ondrej/php && \
    rm -rf /var/lib/apt/lists/*

## PHP extensions are a go!
RUN \
  apt-get update && \
  apt-get install \
    nginx \
    php7.3-fpm \
    php7.3-cli \
    php7.3-mysql \
    php7.3-mysqli \
    php7.3-memcached \
    php7.3-curl \
    php7.3-dom \
    php7.3-exif \
    php7.3-ftp \
    php7.3-gd \
    php7.3-iconv \
    php7.3-mbstring \
    php7.3-pdo \
    php7.3-posix \
    php7.3-soap \
    php7.3-zip \
    php7.3-ldap \
    php7.3-bcmath \
    php7.3-calendar \
    php7.3-gettext \
    php7.3-json \
    php7.3-apcu \
    php7.3-phar \
    php7.3-sockets \
    php7.3-tidy \
    php7.3-wddx \
    php7.3-xmlreader \
    php7.3-xsl \
    php7.3-opcache \
    php7.3-imagick \
    php7.3-ctype \
    php7.3-sqlite3 \
    php7.3-redis \
    php7.3-intl \
    --no-install-recommends -y && \
    rm -rf /var/lib/apt/lists/*

## Add Composer globally
RUN curl -sS https://getcomposer.org/installer | php \
    && mv composer.phar /usr/local/bin/composer \
    && chmod a+x /usr/local/bin/composer

## Add Atatus GPG key and repo
RUN apt-get install curl --no-install-recommends -y && \
  curl https://s3.amazonaws.com/atatus-artifacts/gpg/atatus.gpg | apt-key add - && \
  echo "deb https://s3.amazonaws.com/atatus-artifacts/atatus-php/debian stable main" \
  | tee -a /etc/apt/sources.list.d/atatus-php-agent.list && \
  apt-get update && \
  apt-get install atatus-php-agent --no-install-recommends -y && \
  apt-get remove curl -y && \
  rm -rf /var/lib/apt/lists/*

# supervisor definitions for running nginx and php
ADD conf/supervisor/nginx.conf /etc/supervisor/conf.d/nginx.conf
ADD conf/supervisor/php.conf /etc/supervisor/conf.d/php.conf

# Entrypoint and runner scripts
ADD scripts/boot.sh /boot.sh
ADD scripts/boot-web.sh /boot-web.sh
ADD scripts/boot-worker.sh /boot-worker.sh

# Modify PHP-FPM configuration files to set common properties and listen on socket
#RUN sed -i "s/;date.timezone =.*/date.timezone = UTC/" /etc/php/7.3/cli/php.ini
#RUN sed -i "s/;date.timezone =.*/date.timezone = UTC/" /etc/php/7.3/fpm/php.ini
##RUN sed -i "s/display_errors = Off/display_errors = On/" /etc/php/7.3/fpm/php.ini
#RUN sed -i "s/upload_max_filesize = .*/upload_max_filesize = 100M/" /etc/php/7.3/fpm/php.ini
#RUN sed -i "s/post_max_size = .*/post_max_size = 12M/" /etc/php/7.3/fpm/php.ini
#RUN sed -i "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/" /etc/php/7.3/fpm/php.ini
#RUN sed -i -e "s/pid =.*/pid = \/var\/run\/php7.3-fpm.pid/" /etc/php/7.3/fpm/php-fpm.conf
#RUN sed -i -e "s/error_log =.*/error_log = \/proc\/self\/fd\/2/" /etc/php/7.3/fpm/php-fpm.conf
## RUN sed -i -e "s/;daemonize\s*=\s*yes/daemonize = no/g" /etc/php/7.1/fpm/php-fpm.conf
##RUN sed -i "s/listen = .*/listen = \/var\/run\/php\/php7.1-fpm.sock/" /etc/php/7.3/fpm/pool.d/www.conf
##RUN sed -i "s/;catch_workers_output = .*/catch_workers_output = yes/" /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i "s/listen = .*/listen = \/var\/run\/php7.3-fpm.sock/" /etc/php/7.3/fpm/pool.d/www.conf
RUN sed -i -e "s/pid =.*/pid = \/var\/run\/php7.3-fpm.pid/" /etc/php/7.3/fpm/php-fpm.conf

RUN chmod +x /boot.sh && \
  chmod +x /boot-web.sh && \
  chmod +x /boot-worker.sh

ENTRYPOINT [ "/boot.sh" ]
