FROM ubuntu:bionic
LABEL maintainer="devops@nhsx.uk"
LABEL php="7.3"
ENV DEBIAN_FRONTEND noninteractive

RUN \
  apt-get update && \
  apt-get install \
    composer \
    curl \
    gpg-agent \
    software-properties-common \
    supervisord \
    --no-install-recommends -y && \
    add-apt-repository -y ppa:ondrej/nginx-mainline && \
    add-apt-repository -y ppa:ondrej/php && \
    rm -rf /var/lib/apt/lists/*

## PHP extensions are a go!
RUN \
  apt-get update && \
  apt-get install \
    nginx \
    php7.3-fpm \
    php7.3-cli \
    php7.3-mysql \
    php7.3-mysqli \
    php7.3-memcached \
    php7.3-curl \
    php7.3-dom \
    php7.3-exif \
    php7.3-ftp \
    php7.3-gd \
    php7.3-iconv \
    php7.3-mbstring \
    php7.3-pdo \
    php7.3-posix \
    php7.3-soap \
    php7.3-zip \
    php7.3-ldap \
    php7.3-bcmath \
    php7.3-calendar \
    php7.3-gettext \
    php7.3-json \
    php7.3-apcu \
    php7.3-phar \
    php7.3-sockets \
    php7.3-tidy \
    php7.3-wddx \
    php7.3-xmlreader \
    php7.3-xsl \
    php7.3-opcache \
    php7.3-imagick \
    php7.3-ctype \
    php7.3-sqlite3 \
    php7.3-redis \
    php7.3-intl \
    --no-install-recommends -y && \
    rm -rf /var/lib/apt/lists/*

## Add Atatus GPG key and repo
RUN apt-get install curl --no-install-recommends -y && \
  curl https://s3.amazonaws.com/atatus-artifacts/gpg/atatus.gpg | apt-key add - && \
  echo "deb https://s3.amazonaws.com/atatus-artifacts/atatus-php/debian stable main" \
  | tee -a /etc/apt/sources.list.d/atatus-php-agent.list && \
  apt-get update && \
  apt-get install atatus-php-agent --no-install-recommends -y && \
  apt-get remove curl -y && \
  rm -rf /var/lib/apt/lists/*

# Entrypoint and runner scripts
ADD scripts/boot.sh /boot.sh
ADD scripts/boot-web.sh /boot-web.sh
ADD scripts/boot-worker.sh /boot-worker.sh
RUN chmod 755 /boot-web.sh && \
  chmod 755 /boot-worker.sh

ENTRYPOINT [ "/boot.sh" ]