#!/usr/bin/with-contenv bash
set -e

if [ "$CONTAINERROLE" == "worker" ]; then
  # this line here is what we should have to get rid of the hard link error
  touch /etc/crontab /etc/cron.*/*
  #exec cron -f
  export LOG_STREAM="/tmp/cronout"
  mkfifo $$LOG_STREAM && chmod 777 $$LOG_STREAM && echo -e "$$(env | sed 's/=\\(.*\\)/=\"\\1\"/')\n$$(cat /etc/cron.d/crontab)" > /etc/cron.d/tasks && cron -f | tail -f $$LOG_STREAM"
fi
