#!/usr/bin/with-contenv sh
set -e

if [ "$CONTAINERROLE" == "worker" ]; then
  # this line here is what we should have to get rid of the hard link error
  touch /etc/crontab /etc/cron.*/*
  exec cron -f
fi